name: Nightly Build

on:
  push:
    branches:
      - main
      - build
      - slint

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"

      - name: Build
        run: cargo build -p app --release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: |
            target/release/*.exe
